#include "BasicArduino.h"

namespace HardwareAbstraction {



int BasicArduino::digitalRead(int pin)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--26492f5f:149af006a41:-8000:0000000000000AF3 begin
{
	return 1;
}
// section 127-0-1-1--26492f5f:149af006a41:-8000:0000000000000AF3 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int BasicArduino::digitalWrite(int pin, int value)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--26492f5f:149af006a41:-8000:0000000000000AF7 begin
{
	return value;
}
// section 127-0-1-1--26492f5f:149af006a41:-8000:0000000000000AF7 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int BasicArduino::analogRead(int pin)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--26492f5f:149af006a41:-8000:0000000000000AFB begin
{
	return 1;
}
// section 127-0-1-1--26492f5f:149af006a41:-8000:0000000000000AFB end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int BasicArduino::analogWrite(int pin, int value)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--26492f5f:149af006a41:-8000:0000000000000AFE begin
{
	return 1;
}
// section 127-0-1-1--26492f5f:149af006a41:-8000:0000000000000AFE end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

} /* End of namespace HardwareAbstraction */
