#include "DigitalReadOperation.h"

namespace Operations {




Json::Value DigitalReadOperation::execute()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--1fc1d787:149a46700ab:-8000:0000000000000AC9 begin
{
	Json::Value execute_root(Json::objectValue);
	execute_root["operationString"] = "digitalRead";
	execute_root["pin"] = this->getPin();
	// execute_root["value"] = this->getValue();
	// std::cout << this->getPin();
	// std::vector<std::string> vec;

	// vec.push_back("digitalRead");
	// vec.push_back(std::to_string(this->getPin()));
	// vec.push_back(std::to_string(this->getValue()));

	if(getPin() >= 0) {
		int value = controller->digitalRead(getPin());

		// std::cout << value << std::endl;
		if(value) {
			execute_root["value"] = value;
			execute_root["status"] = "success";
		};				
	} else {
			execute_root["value"] = -1;
			execute_root["status"] = "failed";
	}

	return execute_root;
}
// section 127-0-1-1--1fc1d787:149a46700ab:-8000:0000000000000AC9 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Json::Value DigitalReadOperation::getExecutionTree(){

	Json::Value operation;
	operation["operationString"] = "digitalRead";
	operation["pin"] = getPin();
	return operation;
}

} /* End of namespace Operations */
