#include "DigitalWriteOperation.h"
namespace Operations {




Json::Value DigitalWriteOperation::execute()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--1fc1d787:149a46700ab:-8000:0000000000000AC1 begin
{
	// std::vector<std::string> vec;
	Json::Value execute_root(Json::objectValue);
	execute_root["operationString"] = "digitalWrite";
	execute_root["pin"] = this->getPin();
	execute_root["value"] = this->getValue();

	if(getPin() >= 0 && getValue() >= 0) {
		if(controller->digitalWrite(getPin(), getValue())) {
			execute_root["status"] = "success";
		} else {
			execute_root["status"] = "failed";
		}				
	} else {
		execute_root["status"] = "failed";
	}

	return execute_root;
}

Json::Value DigitalWriteOperation::getExecutionTree() {
	// std::string ret_str = " { operation: digitalWrite, pin: " + std::to_string(getPin()) + ", value: " + std::to_string(getValue()) + " }";
	// return ret_str;

	Json::Value operation;
	operation["operationString"] = "digitalWrite";
	operation["pin"] = getPin();
	operation["value"] = getValue();
	// operation->SetObject();
	return operation;

}
 /* End of namespace Operations */
}